name: weather_app
description: Weather App - Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  cached_network_image: ^3.3.0
  cupertino_icons: ^1.0.2
  dio: ^5.3.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.4
  freezed_annotation: ^2.4.1
  go_router: ^12.0.0
  json_annotation: ^4.8.1

dev_dependencies:
  blendthink_lints: ^3.0.0
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  go_router_builder: ^2.3.3
  json_serializable: ^6.7.1
  mockito: ^5.4.2

# Config generate when build
flutter_gen:
  output: lib/gen/
  line_lenght: 160
  null_safety: true

  integrations:
    flutter_svg: true

  assets:
    enabled: true

  colors:
    enabled: true
    inputs:
      - assets/color/colors.xml

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/images/
